apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "grpc.fullname" . }}
  labels:
    {{- include "grpc.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT: {{ .Values.env.aspnetcoreEnvironment | quote }}
  ASPNETCORE_URLS: {{ .Values.env.urls | quote }}
  {{- if .Values.env.grpcUrl }}
  Kestrel__Endpoints__Grpc__Url: {{ .Values.env.grpcUrl | quote }}
  Kestrel__Endpoints__Grpc__Protocols: Http2
  {{- end }}
  {{- range $key, $value := .Values.env.extra }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
