apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "grpc.fullname" . }}
  labels:
    {{- include "grpc.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "grpc.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "grpc.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "grpc.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}
      containers:
        - name: grpc
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpcTargetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "grpc.fullname" . }}
            {{- if .Values.secret.data }}
            - secretRef:
                name: {{ include "grpc.fullname" . }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          resources:
            {{- include "grpc.resources" . | nindent 12 }}
