{{- if .Values.secret.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "grpc.fullname" . }}
  labels:
    {{- include "grpc.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $key, $value := .Values.secret.data }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
