{{- $bookingsService := include "sol9.fullname" (dict "root" . "component" "bookings-api") -}}
{{- $ordersService := include "sol9.fullname" (dict "root" . "component" "orders-api") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sol9.fullname" (dict "root" . "component" "gateway") }}
  labels:
    {{- include "sol9.labels" (dict "root" . "component" "gateway") | nindent 4 }}
spec:
  replicas: {{ .Values.gateway.replicaCount }}
  selector:
    matchLabels:
      {{- include "sol9.selectorLabels" (dict "root" . "component" "gateway") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sol9.selectorLabels" (dict "root" . "component" "gateway") | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: gateway
          image: "{{ .Values.images.gateway.repository }}:{{ .Values.images.gateway.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          env:
            - name: ASPNETCORE_URLS
              value: "http://0.0.0.0:{{ .Values.global.service.port }}"
            - name: ASPNETCORE_ENVIRONMENT
              value: "{{ .Values.global.env.aspnetcoreEnvironment }}"
            - name: ReverseProxy__Clusters__bookings-cluster__Destinations__bookings-1__Address
              value: "http://{{ $bookingsService }}:{{ .Values.global.service.port }}"
            - name: ReverseProxy__Clusters__orders-cluster__Destinations__orders-1__Address
              value: "http://{{ $ordersService }}:{{ .Values.global.service.port }}"
          ports:
            - name: http
              containerPort: {{ .Values.global.service.port }}
          livenessProbe:
            tcpSocket:
              port: {{ .Values.global.service.port }}
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: {{ .Values.global.service.port }}
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources.default | nindent 12 }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
