{{- if .Values.rollouts.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sol9.fullname" (dict "root" . "component" "orders-api-preview") }}
  labels:
    {{- include "sol9.labels" (dict "root" . "component" "orders-api") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.global.service.port }}
      targetPort: {{ .Values.global.service.port }}
    - name: grpc
      port: {{ .Values.global.service.grpcPort }}
      targetPort: {{ .Values.global.service.grpcPort }}
  selector:
    {{- include "sol9.selectorLabels" (dict "root" . "component" "orders-api") | nindent 4 }}
{{- end }}
