{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.postgres.host }}
  labels:
    {{- include "sol9.labels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  ports:
    - name: postgres
      port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
  selector:
    {{- include "sol9.selectorLabels" (dict "root" . "component" "postgres") | nindent 4 }}
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sol9.fullname" (dict "root" . "component" "postgres") }}
  labels:
    {{- include "sol9.labels" (dict "root" . "component" "postgres") | nindent 4 }}
spec:
  serviceName: {{ .Values.postgres.host }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "sol9.selectorLabels" (dict "root" . "component" "postgres") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sol9.selectorLabels" (dict "root" . "component" "postgres") | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}
          ports:
            - containerPort: {{ .Values.postgres.port }}
          env:
            - name: POSTGRES_DB
              value: "{{ .Values.postgres.database }}"
            - name: POSTGRES_USER
              value: "{{ .Values.postgres.username }}"
            - name: POSTGRES_PASSWORD
              value: "{{ .Values.postgres.password }}"
          resources:
            {{- toYaml .Values.resources.default | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: {{ .Values.postgres.storage }}
{{- end }}
