{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.redis.host }}
  labels:
    {{- include "sol9.labels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  ports:
    - name: redis
      port: {{ .Values.redis.port }}
      targetPort: {{ .Values.redis.port }}
  selector:
    {{- include "sol9.selectorLabels" (dict "root" . "component" "redis") | nindent 4 }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sol9.fullname" (dict "root" . "component" "redis") }}
  labels:
    {{- include "sol9.labels" (dict "root" . "component" "redis") | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sol9.selectorLabels" (dict "root" . "component" "redis") | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sol9.selectorLabels" (dict "root" . "component" "redis") | nindent 8 }}
    spec:
      automountServiceAccountToken: false
      containers:
        - name: redis
          image: {{ .Values.redis.image }}
          ports:
            - containerPort: {{ .Values.redis.port }}
          resources:
            {{- toYaml .Values.resources.default | nindent 12 }}
{{- end }}
