{{- $pgHost := include "sol9.postgresHost" . -}}
{{- $pgPort := .Values.postgres.port -}}
{{- $pgDb := .Values.postgres.database -}}
{{- $pgUser := .Values.postgres.username -}}
{{- $pgPassword := .Values.postgres.password -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sol9.secretsName" . }}
  labels:
    {{- include "sol9.labels" (dict "root" . "component" "config") | nindent 4 }}
type: Opaque
stringData:
  ConnectionStrings__Bookings: "Host={{ $pgHost }};Port={{ $pgPort }};Database={{ $pgDb }};Username={{ $pgUser }};Password={{ $pgPassword }}"
  ConnectionStrings__Orders: "Host={{ $pgHost }};Port={{ $pgPort }};Database={{ $pgDb }};Username={{ $pgUser }};Password={{ $pgPassword }}"
  ConnectionStrings__Transponder: "Host={{ $pgHost }};Port={{ $pgPort }};Database={{ $pgDb }};Username={{ $pgUser }};Password={{ $pgPassword }}"
  ConnectionStrings__Redis: "{{ include "sol9.redisConnectionString" . }}"
