{{- if not .Values.rollout.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bookings-api.fullname" . }}
  labels:
    {{- include "bookings-api.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "bookings-api.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "bookings-api.selectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.imagePullSecrets | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bookings-api.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}
      containers:
        - name: bookings-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "bookings-api.fullname" . }}
            - secretRef:
                name: {{ include "bookings-api.fullname" . }}
          {{- if .Values.tls.enabled }}
          volumeMounts:
            - name: tls-cert
              mountPath: {{ .Values.tls.mountPath }}
              readOnly: true
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
              scheme: {{ ternary "HTTPS" "HTTP" .Values.tls.enabled }}
            initialDelaySeconds: {{ .Values.probes.liveness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.liveness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.liveness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.liveness.failureThreshold }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
              scheme: {{ ternary "HTTPS" "HTTP" .Values.tls.enabled }}
            initialDelaySeconds: {{ .Values.probes.readiness.initialDelaySeconds }}
            periodSeconds: {{ .Values.probes.readiness.periodSeconds }}
            timeoutSeconds: {{ .Values.probes.readiness.timeoutSeconds }}
            failureThreshold: {{ .Values.probes.readiness.failureThreshold }}
          resources:
            {{- include "bookings-api.resources" . | nindent 12 }}
      {{- if .Values.tls.enabled }}
      volumes:
        - name: tls-cert
          secret:
            secretName: {{ .Values.tls.secretName }}
      {{- end }}
{{- end }}
