{{- if .Values.pdb.enabled -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "gateway-api.fullname" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "gateway-api.selectorLabels" . | nindent 6 }}
  {{- if .Values.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.pdb.maxUnavailable }}
  {{- else }}
  minAvailable: {{ .Values.pdb.minAvailable }}
  {{- end }}
{{- end }}
