{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway-api.serviceAccountName" . }}
  labels:
    {{- include "gateway-api.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount | default false }}
{{- end -}}
