{{- if .Values.rollout.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "orders-api.previewServiceName" . }}
  labels:
    {{- include "orders-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    {{- include "orders-api.selectorLabels" . | nindent 4 }}
{{- end }}
