kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: sol9
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
      endpoint = ["http://kind-registry:5000"]
nodes:
  - role: control-plane
    image: kindest/node:v1.30.4
    extraPortMappings:
      - containerPort: 30080
        hostPort: 30080
        protocol: TCP
  - role: worker
    image: kindest/node:v1.30.4
  - role: worker
    image: kindest/node:v1.30.4
