apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sol9
  namespace: argocd
spec:
  project: sol9
  source:
    repoURL: https://github.com/Ahmed-Shehzad/Sol9
    targetRevision: HEAD
    path: K8S/helm/sol9
  destination:
    server: https://kubernetes.default.svc
    namespace: sol9
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
