apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: redis
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "redis.fullname" . }}
          ports:
            - name: redis
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- if .Values.auth.enabled }}
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "redis.fullname" . }}
                  key: REDIS_PASSWORD
          args:
            - "--requirepass"
            - "$(REDIS_PASSWORD)"
            - "--port"
            - "{{ .Values.service.port }}"
          {{- else }}
          args:
            - "--port"
            - "{{ .Values.service.port }}"
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
