{{- if .Values.auth.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.fullname" . }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  REDIS_PASSWORD: {{ .Values.auth.password | quote }}
{{- end -}}
