# This is a generated file. Not intended for manual editing.
services:
  sol9:
    build:
      context: "/Users/muhammadahmedshehzad/RiderProjects/Sol9"
      dockerfile: "Sol9/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57412"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "sol9:dev"
    ports:
    - "127.0.0.1:57012:57000"
    - "127.0.0.1:57212:57200"
    - "127.0.0.1:57412:57412"
    volumes:
    - "/Users/muhammadahmedshehzad/RiderProjects/Sol9/Sol9:/app:rw"
    - "/Users/muhammadahmedshehzad/RiderProjects/Sol9:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/home/app/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.0.3/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_02_22_01_47:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
