# This is a generated file. Not intended for manual editing.
services:
  webapplication1:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Sol9"
      dockerfile: "WebApplication1/Dockerfile"
      target: "build"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57402"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "webapplication1:dev"
    ports:
    - "127.0.0.1:57002:57000"
    - "127.0.0.1:57202:57200"
    - "127.0.0.1:57402:57402"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Sol9/WebApplication1:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Sol9:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.1/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_21_20_54_53:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
  webapplication2:
    build:
      context: "/Users/muhammadahmedshehzad/Personal/RiderProjects/Sol9"
      dockerfile: "WebApplication2/Dockerfile"
      target: "build"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-arm64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57403"
    - "--timeout=60"
    environment:
      ASPNETCORE_ENVIRONMENT: "Development"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "webapplication2:dev"
    ports:
    - "127.0.0.1:57003:57000"
    - "127.0.0.1:57203:57200"
    - "127.0.0.1:57403:57403"
    volumes:
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Sol9/WebApplication2:/app:rw"
    - "/Users/muhammadahmedshehzad/Personal/RiderProjects/Sol9:/src:rw"
    - "/Users/muhammadahmedshehzad/.nuget/packages:/root/.nuget/packages"
    - "/Users/muhammadahmedshehzad/.local/share/JetBrains/RiderRemoteDebugger/2025.3.1/LinuxArm64:/opt/JetBrains/RiderDebuggerTools"
    - "/Applications/Rider.app/Contents/bin/backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "/Users/muhammadahmedshehzad/Library/Logs/JetBrains/Rider2025.3/DebuggerWorker/JetBrains.Debugger.Worker.2025_12_21_20_54_53:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
